schema_version: 1

context:
  version: "2.16.0"

package:
  name: moor
  version: ${{ version }}

source:
  url: https://github.com/walles/moor/archive/v${{ version }}.tar.gz
  sha256: 818e19048913cbccc9be893ee60cad6bd977e7ae958e2c6b68007cf67eb079a1

build:
  number: 0

requirements:
  build:
    - ${{ compiler("go-nocgo") }}
    - go-licenses

tests:
  - script:
      - moor --help

about:
  license: BSD-2-Clause
  license_file:
    - LICENSE
    - license-files/
  summary: Nice to use pager for humans
  homepage: https://github.com/walles/moor
  repository: https://github.com/walles/moor

extra:
  recipe-maintainers:
    - danielnachun
